### PR TITLE
[fix] Close connections after non 200 status

### PR DESCRIPTION
**Pull request by dkulyk**
Nginx  handling error on http requests like `/usage`

This PR marks responses as `Connection: close`  for correct behavior.

Also returns 404 response for all other requests. For example `GET /favicon.ico` raised error on connection closing

### CODE REVIEW

**Comment by rennokki** [comment]
I agree on the fallback catch for other endpoints that should throw 404, but i don't get the `end()`'s second parameter. Looking in the documentation for `end()`, there is no second parameter: https://github.com/uNetworking/uWebSockets.js/blob/master/docs/index.d.ts#L66

**Comment by dkulyk** [comment]
This is another method: https://github.com/uNetworking/uWebSockets.js/blob/master/docs/index.d.ts#L149
But in sources second argument is present:
https://github.com/uNetworking/uWebSockets.js/blob/master/src/HttpResponseWrapper.h#L218-L220
this added in https://github.com/uNetworking/uWebSockets.js/commit/6008a08b3820b99033b83d853d7baf83a0bbe0e7

**Comment by dkulyk** [comment]
Method definition is updated in https://github.com/uNetworking/uWebSockets.js/pull/596

**Comment by rennokki** [comment]
@dkulyk [Currently, the package is locked @ 19.2.0](https://github.com/soketi/pws/blob/0.3.0/package.json#L46), 19.3 is already released, might just wait for 19.4 to be released and make it work with the new definition. Setting it to `#master` would be a bad idea.

**Pull request closed without merging**
